all: false
dir: 'mocks'
filename: mocks.go
force-file-write: true
structname: '{{.Mock}}{{.InterfaceName}}'
pkgname: '{{.SrcPackageName}}_mocks'
packages:
  github.com/Alhanaqtah/netra:
    interfaces:
      Backend:
